[build]
  command = "yarn build"
  publish = "public"
  NODE_VERSION = "12"

[[redirects]]
  from = "https://blog.oscartegiffel.com"
  to = "https://oscartegiffel.com/blog"
  status = 301
  force = true # COMMENT: ensure that we always redirect